/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef __USB_HOST_INTERFACE_0_HID_MOUSE_H__
#define __USB_HOST_INTERFACE_0_HID_MOUSE_H__

/*******************************************************************************
 * API
 ******************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif
/*!
 * @brief host mouse initialization function.
 *
 * This function handles mouse class-specific setup.
 *
 * @return A USB error code or kStatus_USB_Success.
 */
usb_status_t USB_HostInterface0HidMouseInit(void);

/*!
* @brief host mouse task function.
*
* This function implements the host mouse action, it is used to create task.
*/
void USB_HostInterface0HidMouseTask(void);

/*!
 * @brief host mouse callback function.
 *
 * This function should be called in the host callback function.
 *
 * @param deviceHandle          device handle.
 * @param configurationHandle   attached device configuration descriptor information.
 * @param eventCode             callback event code, please reference to enumeration host_event_t.
 * @param processedInterfaces   array of already processed interface flags.
 *
 * @retval kStatus_USB_Success              The host is initialized successfully.
 * @retval kStatus_USB_NotSupported         The configuration doesn't contain hid mouse interface.
 */
usb_status_t USB_HostInterface0HidMouseEvent(usb_device_handle deviceHandle,
                                          usb_host_configuration_handle configurationHandle,
                                          uint32_t eventCode, uint8_t *processedInterfaces);

#if defined(__cplusplus)
}
#endif
#endif /* __USB_HOST_INTERFACE_0_HID_MOUSE_H__ */
