/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Peripherals v15.0
processor: MCXN947
package_id: MCXN947VDF
mcu_data: ksdk2_0
processor_version: 24.12.10
board: FRDM-MCXN947
functionalGroups:
- name: BOARD_InitPeripherals
  UUID: 7568ace5-20dc-4750-97a1-829bebad0f13
  called_from_default_init: true
  selectedCore: cm33_core0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'system'
- type_id: 'system'
- global_system_definitions:
  - user_definitions: '\n'
  - user_includes: '#include "fsl_phylan8720a.h"'
  - global_init: ''
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'gpio_adapter_common'
- type_id: 'gpio_adapter_common'
- global_gpio_adapter_common:
  - quick_selection: 'default'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'uart_cmsis_common'
- type_id: 'uart_cmsis_common'
- global_USART_CMSIS_common:
  - quick_selection: 'default'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "peripherals.h"

/***********************************************************************************************************************
 * BOARD_InitPeripherals functional group
 **********************************************************************************************************************/
/***********************************************************************************************************************
 * MPU initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'MPU'
- type: 'mpu_utility'
- mode: 'MPU'
- custom_name_enabled: 'false'
- type_id: 'mpu_utility'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'MPU'
- config_sets:
  - mpu_init:
    - mpuInit: 'disabled'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/* Empty initialization function (commented out)
static void MPU_init(void) {
} */

/***********************************************************************************************************************
 * NVIC initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'NVIC'
- type: 'nvic'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'nvic'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'NVIC'
- config_sets:
  - nvic:
    - interrupt_table:
      - 0: []
      - 1: []
    - interrupts:
      - 0:
        - channelId: 'usb_interrupt'
        - interrupt_t:
          - IRQn: 'USB0_FS_IRQn'
          - enable_interrrupt: 'enabled'
          - enable_priority: 'false'
          - priority: '0'
          - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/* Empty initialization function (commented out)
static void NVIC_init(void) {
} */

/***********************************************************************************************************************
 * LP_FLEXCOMM4 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'LP_FLEXCOMM4'
- type: 'lpflexcomm_lpspi'
- mode: 'interrupt'
- custom_name_enabled: 'false'
- type_id: 'lpflexcomm_lpspi_2.2.0'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'LP_FLEXCOMM4'
- config_sets:
  - interrupt:
    - interrupt_sources: 'kLPSPI_TxInterruptEnable kLPSPI_RxInterruptEnable'
    - enableInterrupt: 'true'
    - interrupt:
      - IRQn: 'LP_FLEXCOMM4_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
  - main:
    - mode: 'kLPSPI_Master'
    - clockSource: 'clk_src0'
    - clockSourceFreq: 'ClocksTool_DefaultInit'
    - master:
      - baudRateBps: '500000'
      - bitsPerFrame: '8'
      - cpol: 'kLPSPI_ClockPolarityActiveHigh'
      - cpha: 'kLPSPI_ClockPhaseFirstEdge'
      - direction: 'kLPSPI_MsbFirst'
      - pcsToSckDelayInNanoSec: '1000'
      - lastSckToPcsDelayInNanoSec: '1000'
      - betweenTransferDelayInNanoSec: '1000'
      - whichPcs: 'kLPSPI_Pcs0'
      - pcsActiveHighOrLow: 'kLPSPI_PcsActiveLow'
      - pinCfg: 'kLPSPI_SdiInSdoOut'
      - pcsFunc: 'kLPSPI_PcsAsCs'
      - dataOutConfig: 'kLpspiDataOutRetained'
      - enableInputDelay: 'false'
    - set_FifoWaterMarks: 'false'
    - fifoWaterMarks:
      - txWatermark: '0'
      - rxWatermark: '0'
    - allPcsPolarityEnable: 'false'
    - allPcsPolarity:
      - kLPSPI_Pcs1Active: 'kLPSPI_PcsActiveLow'
      - kLPSPI_Pcs2Active: 'kLPSPI_PcsActiveLow'
      - kLPSPI_Pcs3Active: 'kLPSPI_PcsActiveLow'
    - quick_selection: 'qs_master'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const lpspi_master_config_t LP_FLEXCOMM4_config = {
  .baudRate = 500000UL,
  .bitsPerFrame = 8UL,
  .cpol = kLPSPI_ClockPolarityActiveHigh,
  .cpha = kLPSPI_ClockPhaseFirstEdge,
  .direction = kLPSPI_MsbFirst,
  .pcsToSckDelayInNanoSec = 1000UL,
  .lastSckToPcsDelayInNanoSec = 1000UL,
  .betweenTransferDelayInNanoSec = 1000UL,
  .whichPcs = kLPSPI_Pcs0,
  .pcsActiveHighOrLow = kLPSPI_PcsActiveLow,
  .pinCfg = kLPSPI_SdiInSdoOut,
  .pcsFunc = kLPSPI_PcsAsCs,
  .dataOutConfig = kLpspiDataOutRetained,
  .enableInputDelay = false
};

static void LP_FLEXCOMM4_init(void) {
  LPSPI_MasterInit(LP_FLEXCOMM4_PERIPHERAL, &LP_FLEXCOMM4_config, LP_FLEXCOMM4_CLOCK_FREQ);
  /* Enable interrupt sources */
  LPSPI_EnableInterrupts(LP_FLEXCOMM4_PERIPHERAL, (kLPSPI_TxInterruptEnable | kLPSPI_RxInterruptEnable));
  /* Enable interrupt LP_FLEXCOMM4_IRQN request in the NVIC */
  EnableIRQ(LP_FLEXCOMM4_IRQN);
}

/***********************************************************************************************************************
 * WUU0 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'WUU0'
- type: 'wuu'
- mode: 'General'
- custom_name_enabled: 'false'
- type_id: 'wuu_2.1.0'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'WUU0'
- config_sets:
  - fsl_wuu:
    - wuu_module_config:
      - 0:
        - wuu_internal_wakeup_module_event: 'kWUU_InternalModuleInterrupt'
        - wuu_module_interrupt: 'interrupt_module0'
    - wuu_external_pin_config:
      - 0:
        - wuu_pin_external: 'P.8'
        - filterEnable: 'false'
        - wuu_external_wakeup_pin_config:
          - edge: 'kWUU_ExternalPinDisable'
          - event: 'kWUU_ExternalPinInterrupt'
          - mode: 'kWUU_ExternalPinActiveDSPD'
    - externalPinsClearingFlag: 'false'
    - interrupts:
      - enableInterrupt: 'false'
      - interrupt:
        - IRQn: 'WUU_IRQn'
        - enable_interrrupt: 'enabled'
        - enable_priority: 'false'
        - priority: '0'
        - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const wuu_external_wakeup_pin_config_t WUU0_external_wakeup_pin_config_8 = {
  .edge = kWUU_ExternalPinDisable,
  .event = kWUU_ExternalPinInterrupt,
  .mode = kWUU_ExternalPinActiveDSPD
};

static void WUU0_init(void) {
  /* WUU0 internal module source Interrupt module 0 configuration */
  WUU_SetInternalWakeUpModulesConfig(WUU0_PERIPHERAL, WUU0_MODULE_INTERRUPT_0, kWUU_InternalModuleInterrupt);
  /* WUU0 external pin 8 configuration */
  WUU_SetExternalWakeUpPinsConfig(WUU0_PERIPHERAL, WUU0_EXTERN_PIN_8, &WUU0_external_wakeup_pin_config_8);
}

/***********************************************************************************************************************
 * LP_FLEXCOMM0 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'LP_FLEXCOMM0'
- type: 'lpflexcomm_lpuart'
- mode: 'polling'
- custom_name_enabled: 'false'
- type_id: 'lpflexcomm_lpuart_2.3.0'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'LP_FLEXCOMM0'
- config_sets:
  - fsl_lpuart:
    - lpuartConfig:
      - timingConfig:
        - clockSource: 'LPFLEXCOMMFunctionClock'
        - lpuartSrcClkFreq: 'BOARD_BootClockPLL150M'
        - baudRateBpsStr: '115200'
      - parityMode: 'kLPUART_ParityDisabled'
      - dataBitsCount: 'kLPUART_EightDataBits'
      - isMsb: 'false'
      - stopBitCount: 'kLPUART_OneStopBit'
      - enableMatchAddress1: 'false'
      - matchAddress1: '0'
      - enableMatchAddress2: 'false'
      - matchAddress2: '0'
      - txFifoWatermark: '0'
      - rxFifoWatermark: '1'
      - enableRxRTS: 'false'
      - rtsDelayValue: '1'
      - enableTxCTS: 'false'
      - txCtsSource: 'kLPUART_CtsSourcePin'
      - txCtsConfig: 'kLPUART_CtsSampleAtStart'
      - rxIdleType: 'kLPUART_IdleTypeStartBit'
      - rxIdleConfig: 'kLPUART_IdleCharacter1'
      - enableSingleWire: 'false'
      - enableTx: 'true'
      - enableRx: 'true'
      - timeoutConfig:
        - rxExtendedTimeoutValue: '0'
        - txExtendedTimeoutValue: '0'
        - rxCounter0:
          - enableCounter: 'false'
          - timeoutCondition: 'kLPUART_TimeoutAfterCharacters'
          - timeoutValue: '0'
        - rxCounter1:
          - enableCounter: 'false'
          - timeoutCondition: 'kLPUART_TimeoutAfterCharacters'
          - timeoutValue: '0'
        - txCounter0:
          - enableCounter: 'false'
          - timeoutCondition: 'kLPUART_TimeoutAfterCharacters'
          - timeoutValue: '0'
        - txCounter1:
          - enableCounter: 'false'
          - timeoutCondition: 'kLPUART_TimeoutAfterCharacters'
          - timeoutValue: '0'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const lpuart_config_t LP_FLEXCOMM0_config = {
  .baudRate_Bps = 115200UL,
  .parityMode = kLPUART_ParityDisabled,
  .dataBitsCount = kLPUART_EightDataBits,
  .isMsb = false,
  .stopBitCount = kLPUART_OneStopBit,
  .txFifoWatermark = 0U,
  .rxFifoWatermark = 1U,
  .enableRxRTS = false,
  .enableTxCTS = false,
  .txCtsSource = kLPUART_CtsSourcePin,
  .txCtsConfig = kLPUART_CtsSampleAtStart,
  .rxIdleType = kLPUART_IdleTypeStartBit,
  .rxIdleConfig = kLPUART_IdleCharacter1,
  .enableSingleWire = false,
  .rtsDelay = 0,
  .enableTx = true,
  .enableRx = true,
  .timeoutConfig = {
    .rxExtendedTimeoutValue = 0U,
    .txExtendedTimeoutValue = 0U,
    .rxCounter0 = {
      .enableCounter = false,
      .timeoutCondition = kLPUART_TimeoutAfterCharacters,
      .timeoutValue = 0U
    },
    .rxCounter1 = {
      .enableCounter = false,
      .timeoutCondition = kLPUART_TimeoutAfterCharacters,
      .timeoutValue = 0U
    },
    .txCounter0 = {
      .enableCounter = false,
      .timeoutCondition = kLPUART_TimeoutAfterCharacters,
      .timeoutValue = 0U
    },
    .txCounter1 = {
      .enableCounter = false,
      .timeoutCondition = kLPUART_TimeoutAfterCharacters,
      .timeoutValue = 0U
    }
  }
};

static void LP_FLEXCOMM0_init(void) {
  LPUART_Init(LP_FLEXCOMM0_PERIPHERAL, &LP_FLEXCOMM0_config, LP_FLEXCOMM0_CLOCK_SOURCE);
}

/***********************************************************************************************************************
 * FLEXIO0 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'FLEXIO0'
- type: 'flexio_reg'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'flexio_reg'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'FLEXIO0'
- config_sets:
  - generalConfig:
    - clkConfig:
      - clockSource: 'FlexIoClock'
      - clockSourceFreq: 'ClocksTool_DefaultInit'
    - flexioConfig:
      - FLEXEN: 'false'
      - FASTACC: 'false'
      - DBGE: 'false'
      - DOZEN: 'true'
    - tabs:
      - timers_tab:
        - timers:
          - 0:
            - uid: '-1'
            - id: 'TIMER0'
            - number: '0'
            - description: ''
            - TIMOD: '0'
            - ONETIM: '0'
            - TSTART: '0'
            - TSTOP: '0'
            - TRGSRC: '0'
            - TRGSEL: '0'
            - TRGPOL: '0'
            - PINSEL: '0'
            - PINCFG: '0'
            - PINPOL: '0'
            - PININS: '0'
            - TIMENA: '0'
            - TIMDIS: '0'
            - TIMRST: '0'
            - TIMOUT: '0'
            - TIMDEC: '0'
            - timerClockFreqCustomStr: ''
            - TEIE: 'false'
            - TSDE: 'false'
            - params: []
      - shifters_tab:
        - shifters:
          - 0:
            - uid: '-1'
            - id: 'SHIFTER0'
            - number: '0'
            - description: ''
            - SMOD: '0'
            - SSIZE: '0'
            - LATST: '0'
            - SSTART: '0'
            - SSTOP: '0'
            - TIMSEL: '-1'
            - TIMPOL: '0'
            - INSRC: '0'
            - PINSEL: '0'
            - PINCFG: '0'
            - PINPOL: '0'
            - PWIDTH: '1'
            - SSIE: 'false'
            - SEIE: 'false'
            - SSDE: 'false'
            - params: []
      - pins_overview:
        - 0:
          - PSIE: 'false'
          - PRE: 'false'
          - PFE: 'false'
          - OUTE: 'false'
          - OUTD: '0'
        - 1:
          - PSIE: 'false'
          - PRE: 'false'
          - PFE: 'false'
          - OUTE: 'false'
          - OUTD: '0'
        - 2:
          - PSIE: 'false'
          - PRE: 'false'
          - PFE: 'false'
          - OUTE: 'false'
          - OUTD: '0'
        - 3:
          - PSIE: 'false'
          - PRE: 'false'
          - PFE: 'false'
          - OUTE: 'false'
          - OUTD: '0'
        - 4:
          - PSIE: 'false'
          - PRE: 'false'
          - PFE: 'false'
          - OUTE: 'false'
          - OUTD: '0'
        - 5:
          - PSIE: 'false'
          - PRE: 'false'
          - PFE: 'false'
          - OUTE: 'false'
          - OUTD: '0'
        - 6:
          - PSIE: 'false'
          - PRE: 'false'
          - PFE: 'false'
          - OUTE: 'false'
          - OUTD: '0'
        - 7:
          - PSIE: 'false'
          - PRE: 'false'
          - PFE: 'false'
          - OUTE: 'false'
          - OUTD: '0'
        - 8:
          - PSIE: 'false'
          - PRE: 'false'
          - PFE: 'false'
          - OUTE: 'false'
          - OUTD: '0'
        - 9:
          - PSIE: 'false'
          - PRE: 'false'
          - PFE: 'false'
          - OUTE: 'false'
          - OUTD: '0'
        - 10:
          - PSIE: 'false'
          - PRE: 'false'
          - PFE: 'false'
          - OUTE: 'false'
          - OUTD: '0'
        - 11:
          - PSIE: 'false'
          - PRE: 'false'
          - PFE: 'false'
          - OUTE: 'false'
          - OUTD: '0'
        - 12:
          - PSIE: 'false'
          - PRE: 'false'
          - PFE: 'false'
          - OUTE: 'false'
          - OUTD: '0'
        - 13:
          - PSIE: 'false'
          - PRE: 'false'
          - PFE: 'false'
          - OUTE: 'false'
          - OUTD: '0'
        - 14:
          - PSIE: 'false'
          - PRE: 'false'
          - PFE: 'false'
          - OUTE: 'false'
          - OUTD: '0'
        - 15:
          - PSIE: 'false'
          - PRE: 'false'
          - PFE: 'false'
          - OUTE: 'false'
          - OUTD: '0'
        - 16:
          - PSIE: 'false'
          - PRE: 'false'
          - PFE: 'false'
          - OUTE: 'false'
          - OUTD: '0'
        - 17:
          - PSIE: 'false'
          - PRE: 'false'
          - PFE: 'false'
          - OUTE: 'false'
          - OUTD: '0'
        - 18:
          - PSIE: 'false'
          - PRE: 'false'
          - PFE: 'false'
          - OUTE: 'false'
          - OUTD: '0'
        - 19:
          - PSIE: 'false'
          - PRE: 'false'
          - PFE: 'false'
          - OUTE: 'false'
          - OUTD: '0'
        - 20:
          - PSIE: 'false'
          - PRE: 'false'
          - PFE: 'false'
          - OUTE: 'false'
          - OUTD: '0'
        - 21:
          - PSIE: 'false'
          - PRE: 'false'
          - PFE: 'false'
          - OUTE: 'false'
          - OUTD: '0'
        - 22:
          - PSIE: 'false'
          - PRE: 'false'
          - PFE: 'false'
          - OUTE: 'false'
          - OUTD: '0'
        - 23:
          - PSIE: 'false'
          - PRE: 'false'
          - PFE: 'false'
          - OUTE: 'false'
          - OUTD: '0'
        - 24:
          - PSIE: 'false'
          - PRE: 'false'
          - PFE: 'false'
          - OUTE: 'false'
          - OUTD: '0'
        - 25:
          - PSIE: 'false'
          - PRE: 'false'
          - PFE: 'false'
          - OUTE: 'false'
          - OUTD: '0'
        - 26:
          - PSIE: 'false'
          - PRE: 'false'
          - PFE: 'false'
          - OUTE: 'false'
          - OUTD: '0'
        - 27:
          - PSIE: 'false'
          - PRE: 'false'
          - PFE: 'false'
          - OUTE: 'false'
          - OUTD: '0'
        - 28:
          - PSIE: 'false'
          - PRE: 'false'
          - PFE: 'false'
          - OUTE: 'false'
          - OUTD: '0'
        - 29:
          - PSIE: 'false'
          - PRE: 'false'
          - PFE: 'false'
          - OUTE: 'false'
          - OUTD: '0'
        - 30:
          - PSIE: 'false'
          - PRE: 'false'
          - PFE: 'false'
          - OUTE: 'false'
          - OUTD: '0'
        - 31:
          - PSIE: 'false'
          - PRE: 'false'
          - PFE: 'false'
          - OUTE: 'false'
          - OUTD: '0'
      - external_trigger_IRQ:
        - 0:
          - TRIE: 'false'
        - 1:
          - TRIE: 'false'
        - 2:
          - TRIE: 'false'
        - 3:
          - TRIE: 'false'
        - 4:
          - TRIE: 'false'
        - 5:
          - TRIE: 'false'
        - 6:
          - TRIE: 'false'
        - 7:
          - TRIE: 'false'
    - enable_interrupt: 'false'
    - interrupt:
      - IRQn: 'FLEXIO_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
    - flexio_params: []
    - quick_selection: 'default'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

static void FLEXIO0_init(void) {
  /* Software reset of the FLEXIO0 peripheral. */
  SYSCON0->PRESETCTRL2 |= SYSCON_PRESETCTRL2_FLEXIO_RST_MASK;
  SYSCON0->PRESETCTRL2 &= ~SYSCON_PRESETCTRL2_FLEXIO_RST_MASK;
  /* FlexIO initialization */
  /* Control register initialization, set software reset bit then clear it */
  FLEXIO0->CTRL |= FLEXIO_CTRL_SWRST_MASK;
  FLEXIO0->CTRL &= ~FLEXIO_CTRL_SWRST_MASK;

  /* Write 1 to clear all shifter status */
  FLEXIO0->SHIFTSTAT = 0xFFFFFFFFU;

  /* Write 1 to clear all shifter error */
  FLEXIO0->SHIFTERR = 0xFFFFFFFFU;

  /* Write 1 to clear all timer status */
  FLEXIO0->TIMSTAT = 0xFFFFFFFFU;

#ifdef FLEXIO_TRGSTAT_ETSF_MASK
  /* Write 1 to clear all external trigger status */
  FLEXIO0->TRGSTAT = 0xFFFFFFFFU;
#endif /* FLEXIO_TRGSTAT_ETSF_MASK */

#ifdef FLEXIO_PINSTAT_PSF_MASK
  /* Write 1 to clear all pin status */
  FLEXIO0->PINSTAT = 0xFFFFFFFFU;
#endif /* FLEXIO_PINSTAT_PSF_MASK */

  /* FlexIO shifter 0 initialization */
  /* Shifter configuration register SHIFTCFGn initialization */
#ifdef FLEXIO0_SHIFTCFG0_INIT
  FLEXIO0->SHIFTCFG[0] = FLEXIO0_SHIFTCFG0_INIT;
#else
  FLEXIO0->SHIFTCFG[0] = 0x0U;
#endif /* FLEXIO0_SHIFTCFG0_INIT */
  
  /* Shifter control register SHIFTCTLn initialization */
#ifdef FLEXIO0_SHIFTCTL0_INIT
  FLEXIO0->SHIFTCTL[0] = FLEXIO0_SHIFTCTL0_INIT;
#else
  FLEXIO0->SHIFTCTL[0] = 0x0U;
#endif /* FLEXIO0_SHIFTCTL0_INIT */

  /* Clear the shifter buffer register */
  (void)FLEXIO0->SHIFTBUF[0];

  /* FlexIO timer 0 initialization */
  /* Timer control register configuration register TIMCTLn initialization */
#ifdef FLEXIO0_TIMCTL0_INIT
  FLEXIO0->TIMCTL[0] = FLEXIO0_TIMCTL0_INIT;
#else
  FLEXIO0->TIMCTL[0] = 0x0U;
#endif /* FLEXIO0_TIMCTL0_INIT */

  /* Timer configuration register TIMCFGn initialization */
#ifdef FLEXIO0_TIMCFG0_INIT
  FLEXIO0->TIMCFG[0] = FLEXIO0_TIMCFG0_INIT;
#else
  FLEXIO0->TIMCFG[0] = 0x0U;
#endif /* FLEXIO0_TIMCFG0_INIT */

  /* Timer compare register TIMCMPn initialization */
#ifdef FLEXIO0_TIMCMP0_INIT
  FLEXIO0->TIMCMP[0] = FLEXIO0_TIMCMP0_INIT;
#else
  FLEXIO0->TIMCMP[0] = 0x0U;
#endif /* FLEXIO0_TIMCMP0_INIT */

  /* Shifter status interrupt register initialization */
#ifdef FLEXIO0_SHIFTSIEN_INIT
  FLEXIO0->SHIFTSIEN = FLEXIO0_SHIFTSIEN_INIT;
#else
  FLEXIO0->SHIFTSIEN = 0x0U;
#endif /* FLEXIO0_SHIFTSIEN_INIT */

  /* Shifter error interrupt register initialization */
#ifdef FLEXIO0_SHIFTEIEN_INIT
  FLEXIO0->SHIFTEIEN = FLEXIO0_SHIFTEIEN_INIT;
#else
  FLEXIO0->SHIFTEIEN = 0x0U;
#endif /* FLEXIO0_SHIFTEIEN_INIT */

  /* Timer interrupt register initialization */
#ifdef FLEXIO0_TIMIEN_INIT
  FLEXIO0->TIMIEN = FLEXIO0_TIMIEN_INIT;
#else
  FLEXIO0->TIMIEN = 0x0U;
#endif /* FLEXIO0_TIMIEN_INIT */

  /* Shifter status DMA register initialization */
#ifdef FLEXIO0_SHIFTSDEN_INIT
  FLEXIO0->SHIFTSDEN = FLEXIO0_SHIFTSDEN_INIT;
#else
  FLEXIO0->SHIFTSDEN = 0x0U;
#endif /* FLEXIO0_SHIFTSDEN_INIT */

#ifdef FLEXIO_TIMERSDEN_TSDE_MASK
  /* Timer status DMA register initialization */
#ifdef FLEXIO0_TIMERSDEN_INIT
  FLEXIO0->TIMERSDEN = FLEXIO0_TIMERSDEN_INIT;
#else
  FLEXIO0->TIMERSDEN = 0x0U;
#endif /* FLEXIO0_TIMERSDEN_INIT */
#endif /* FLEXIO_TIMERSDEN_TSDE_MASK */

#ifdef FLEXIO_SHIFTSTATE_STATE_MASK
  /* Shifter state register initialization */
#ifdef FLEXIO0_SHIFTSTATE_INIT
  FLEXIO0->SHIFTSTATE = FLEXIO0_SHIFTSTATE_INIT;
#else
  FLEXIO0->SHIFTSTATE = 0x0U;
#endif /* FLEXIO0_SHIFTSTATE_INIT */
#endif /* FLEXIO_SHIFTSTATE_STATE_MASK */

#ifdef FLEXIO_TRIGIEN_TRIE_MASK
  /* Trigger interrupt enable register initialization */
#ifdef FLEXIO0_TRIGIEN_INIT
  FLEXIO0->TRIGIEN = FLEXIO0_TRIGIEN_INIT;
#else
  FLEXIO0->TRIGIEN = 0x0U;
#endif /* FLEXIO0_TRIGIEN_INIT */
#endif /* FLEXIO_TRIGIEN_TRIE_MASK */

#ifdef FLEXIO_PINIEN_PSIE_MASK
  /* Pin interrupt enable register */
#ifdef FLEXIO0_PINIEN_INIT
  FLEXIO0->PINIEN = FLEXIO0_PINIEN_INIT;
#else
  FLEXIO0->PINIEN = 0x0U;
#endif /* FLEXIO0_PINIEN_INIT */
#endif /* FLEXIO_PINIEN_PSIE_MASK */

#ifdef FLEXIO_PINREN_PRE_MASK
  /* Pin rising edge enable register initialization */
#ifdef FLEXIO0_PINREN_INIT
  FLEXIO0->PINREN = FLEXIO0_PINREN_INIT;
#else
  FLEXIO0->PINREN = 0x0U;
#endif /* FLEXIO0_PINREN_INIT */
#endif /* FLEXIO_PINREN_PRE_MASK */

#ifdef FLEXIO_PINFEN_PFE_MASK
  /* Pin falling edge enable register initialization */
#ifdef FLEXIO0_PINFEN_INIT
  FLEXIO0->PINFEN = FLEXIO0_PINFEN_INIT;
#else
  FLEXIO0->PINFEN = 0x0U;
#endif /* FLEXIO0_PINFEN_INIT */
#endif /* FLEXIO_PINFEN_PFE_MASK */

#ifdef FLEXIO_PINOUTE_OUTE_MASK
  /* Pin output enable register initialization */
#ifdef FLEXIO0_PINOUTE_INIT
  FLEXIO0->PINOUTE = FLEXIO0_PINOUTE_INIT;
#else
  FLEXIO0->PINOUTE = 0x0U;
#endif /* FLEXIO0_PINOUTE_INIT */
#endif /* FLEXIO_PINOUTE_OUTE_MASK */

#ifdef FLEXIO_PINOUTD_OUTD_MASK
  /* Pin output register initialization */
#ifdef FLEXIO0_PINOUTD_INIT
  FLEXIO0->PINOUTD = FLEXIO0_PINOUTD_INIT;
#else
  FLEXIO0->PINOUTD = 0x0U;
#endif /* FLEXIO0_PINOUTD_INIT */
#endif /* FLEXIO_PINOUTD_OUTD_MASK */

#ifdef FLEXIO0_CTRL_INIT
  FLEXIO0->CTRL = (FLEXIO0_CTRL_INIT & ~FLEXIO_CTRL_SWRST_MASK);
#else
  FLEXIO0->CTRL = 0x0U;
#endif /* FLEXIO0_CTRL_INIT */
}

/***********************************************************************************************************************
 * FLEXSPI0 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'FLEXSPI0'
- type: 'flexspi'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'flexspi_2.5.0'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'FLEXSPI0'
- config_sets:
  - fsl_flexspi:
    - flexspiConfig:
      - rxSampleClock: 'kFLEXSPI_ReadSampleClkLoopbackInternally'
      - clockSource: 'FlexSpiClock'
      - clockSourceFreq: 'ClocksTool_DefaultInit'
      - enableSckFreeRunning: 'false'
      - enableCombination: 'false'
      - enableDoze: 'true'
      - enableHalfSpeedAccess: 'false'
      - enableSckBDiffOpt: 'false'
      - enableSameConfigForAll: 'false'
      - seqTimeoutCycleString: '65535'
      - ipGrantTimeoutCycleString: '255'
      - txWatermark: '8'
      - rxWatermark: '8'
      - ahbConfig:
        - enableAHBWriteIpTxFifo: 'false'
        - enableAHBWriteIpRxFifo: 'false'
        - ahbGrantTimeoutCycleString: '255'
        - ahbBusTimeoutCycleString: '65535'
        - resumeWaitCycleString: '32'
        - buffer:
          - 0:
            - priority: '0'
            - masterIndex: '0'
            - bufferSize: '256'
            - enablePrefetch: 'true'
          - 1:
            - priority: '1'
            - masterIndex: '0'
            - bufferSize: '256'
            - enablePrefetch: 'true'
          - 2:
            - priority: '2'
            - masterIndex: '0'
            - bufferSize: '256'
            - enablePrefetch: 'true'
          - 3:
            - priority: '3'
            - masterIndex: '0'
            - bufferSize: '256'
            - enablePrefetch: 'true'
          - 4:
            - priority: '4'
            - masterIndex: '0'
            - bufferSize: '256'
            - enablePrefetch: 'true'
          - 5:
            - priority: '5'
            - masterIndex: '0'
            - bufferSize: '256'
            - enablePrefetch: 'true'
          - 6:
            - priority: '6'
            - masterIndex: '0'
            - bufferSize: '256'
            - enablePrefetch: 'true'
          - 7:
            - priority: '7'
            - masterIndex: '0'
            - bufferSize: '256'
            - enablePrefetch: 'true'
        - enableClearAHBBufferOpt: 'false'
        - enableReadAddressOpt: 'false'
        - enableAHBPrefetch: 'false'
        - enableAHBBufferable: 'false'
        - enableAHBCachable: 'false'
    - flexspiInterrupt:
      - interrupt_sel: ''
      - interrupt_vectors:
        - enableInterrupt: 'false'
        - interrupt:
          - IRQn: 'FLEXSPI0_IRQn'
          - enable_interrrupt: 'enabled'
          - enable_priority: 'false'
          - priority: '0'
          - enable_custom_name: 'false'
    - enableCustomLUT: 'false'
    - lutConfig:
      - flash: 'defaultFlash'
      - lutName: 'defaultLUT'
    - devices_configs: []
    - quick_selection: 'default'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const flexspi_config_t FLEXSPI0_config = {
  .rxSampleClock = kFLEXSPI_ReadSampleClkLoopbackInternally,
  .enableSckFreeRunning = false,
  .enableCombination = false,
  .enableDoze = true,
  .enableHalfSpeedAccess = false,
  .enableSckBDiffOpt = false,
  .enableSameConfigForAll = false,
  .seqTimeoutCycle = 65535,
  .ipGrantTimeoutCycle = 255,
  .txWatermark = 8U,
  .rxWatermark = 8U,
  .ahbConfig = {
    .enableAHBWriteIpTxFifo = false,
    .enableAHBWriteIpRxFifo = false,
    .ahbGrantTimeoutCycle = 255,
    .ahbBusTimeoutCycle = 65535,
    .resumeWaitCycle = 32,
    .buffer = {
      {
        .priority = 0,
        .masterIndex = 0U,
        .bufferSize = 256U,
        .enablePrefetch = true
      },
      {
        .priority = 1,
        .masterIndex = 0U,
        .bufferSize = 256U,
        .enablePrefetch = true
      },
      {
        .priority = 2,
        .masterIndex = 0U,
        .bufferSize = 256U,
        .enablePrefetch = true
      },
      {
        .priority = 3,
        .masterIndex = 0U,
        .bufferSize = 256U,
        .enablePrefetch = true
      },
      {
        .priority = 4,
        .masterIndex = 0U,
        .bufferSize = 256U,
        .enablePrefetch = true
      },
      {
        .priority = 5,
        .masterIndex = 0U,
        .bufferSize = 256U,
        .enablePrefetch = true
      },
      {
        .priority = 6,
        .masterIndex = 0U,
        .bufferSize = 256U,
        .enablePrefetch = true
      },
      {
        .priority = 7,
        .masterIndex = 0U,
        .bufferSize = 256U,
        .enablePrefetch = true
      }
    },
    .enableClearAHBBufferOpt = false,
    .enableReadAddressOpt = false,
    .enableAHBPrefetch = false,
    .enableAHBBufferable = false,
    .enableAHBCachable = false
  }
};

static void FLEXSPI0_init(void) {
  /* FLEXSPI0 peripheral initialization */
  FLEXSPI_Init(FLEXSPI0_PERIPHERAL, &FLEXSPI0_config);
}

/***********************************************************************************************************************
 * CDOG0 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'CDOG0'
- type: 'cdog'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'cdog_2.1.1'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'CDOG0'
- config_sets:
  - general:
    - cdog_config:
      - lock: 'kCDOG_LockCtrl_Unlock'
      - timeout: 'kCDOG_FaultCtrl_NoAction'
      - miscompare: 'kCDOG_FaultCtrl_NoAction'
      - sequence: 'kCDOG_FaultCtrl_NoAction'
      - state: 'kCDOG_FaultCtrl_NoAction'
      - address: 'kCDOG_FaultCtrl_NoAction'
      - irq_pause: 'kCDOG_IrqPauseCtrl_Run'
      - debug_halt: 'kCDOG_DebugHaltCtrl_Run'
    - enable_timers: 'false'
    - timers:
      - instruction: '0'
      - secure: '0'
    - interrupts:
      - enableInterrupt: 'false'
      - interrupt:
        - IRQn: 'CDOG0_IRQn'
        - enable_interrrupt: 'enabled'
        - enable_priority: 'false'
        - priority: '0'
        - enable_custom_name: 'false'
    - quick_selection: 'default'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
cdog_config_t CDOG0_config = {
  .lock = kCDOG_LockCtrl_Unlock,
  .timeout = kCDOG_FaultCtrl_NoAction,
  .miscompare = kCDOG_FaultCtrl_NoAction,
  .sequence = kCDOG_FaultCtrl_NoAction,
  .state = kCDOG_FaultCtrl_NoAction,
  .address = kCDOG_FaultCtrl_NoAction,
  .irq_pause = kCDOG_IrqPauseCtrl_Run,
  .debug_halt = kCDOG_DebugHaltCtrl_Run
};

static void CDOG0_init(void) {
  /* CDOG0 peripheral initialization */
  CDOG_Init(CDOG0_PERIPHERAL, &CDOG0_config);
}

/***********************************************************************************************************************
 * GPIO0_ALIAS1 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'GPIO0_ALIAS1'
- type: 'gpio'
- mode: 'GPIO'
- custom_name_enabled: 'false'
- type_id: 'gpio_2.7.0'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'GPIO0_ALIAS1'
- config_sets:
  - fsl_gpio:
    - enable_irq: 'false'
    - port_interrupt:
      - IRQn: 'GPIO00_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
    - enable_irq_1: 'false'
    - gpio_interrupt_1:
      - IRQn: 'GPIO01_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '1'
      - enable_custom_name: 'false'
    - enable_irq_EFT: 'false'
    - port_interrupt_EFT:
      - IRQn: 'noInt'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '2'
      - enable_custom_name: 'false'
    - quick_selection: 'QS_GPIO_1'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

static void GPIO0_ALIAS1_init(void) {
  /* Make sure, the clock gate for port 0 is enabled (e. g. in pin_mux.c) */
}

/***********************************************************************************************************************
 * CRC0 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'CRC0'
- type: 'crc'
- mode: 'General'
- custom_name_enabled: 'false'
- type_id: 'crc_2.0.1'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'CRC0'
- config_sets:
  - fsl_crc:
    - config:
      - polynomial: '0'
      - seed: '0'
      - reflectIn: 'false'
      - reflectOut: 'false'
      - complementChecksum: 'false'
      - crcBits: 'kCrcBits16'
      - crcResult: 'kCrcFinalChecksum'
    - quick_selection: 'default'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const crc_config_t CRC0_config = {
  .polynomial = 0UL,
  .seed = 0UL,
  .reflectIn = false,
  .reflectOut = false,
  .complementChecksum = false,
  .crcBits = kCrcBits16,
  .crcResult = kCrcFinalChecksum
};

static void CRC0_init(void) {
  CRC_Init(CRC0_PERIPHERAL, &CRC0_config);
}

/***********************************************************************************************************************
 * lwIP initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'lwIP'
- type: 'lwip'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'lwip_2.2.1-rev1'
- functional_group: 'BOARD_InitPeripherals'
- config_sets:
  - lwip_config:
    - mode: 'bm'
    - MEM_SIZE: '(22 * 1024)'
    - MEMP_NUM_PBUF: '15'
    - MEMP_NUM_UDP_PCB: '6'
    - MEMP_NUM_TCP_PCB: '10'
    - MEMP_NUM_TCP_PCB_LISTEN: '6'
    - MEMP_NUM_TCP_SEG: '22'
    - MEMP_NUM_SYS_TIMEOUT: '10'
    - MEMP_NUM_REASSDATA: '2'
    - PBUF_POOL_SIZE: '5'
    - LWIP_SINGLE_NETIF: 'true'
    - LWIP_IPV4: 'true'
    - IP_FORWARD: 'false'
    - IP_REASSEMBLY: 'true'
    - IP_REASS_MAX_PBUFS: '4'
    - IP_FRAG: 'true'
    - IP_DEFAULT_TTL: '255'
    - LWIP_ARP: 'true'
    - LWIP_ICMP: 'true'
    - ICMP_TTL: 'IP_DEFAULT_TTL'
    - LWIP_BROADCAST_PING: 'false'
    - LWIP_MULTICAST_PING: 'false'
    - LWIP_IGMP: 'false'
    - LWIP_DHCP: 'true'
    - LWIP_DHCP_DOES_ACD_CHECK: 'true'
    - LWIP_IPV6: 'false'
    - LWIP_IPV6_NUM_ADDRESSES: '3'
    - LWIP_IPV6_AUTOCONFIG: 'true'
    - LWIP_IPV6_DHCP6: 'false'
    - LWIP_RAW: 'false'
    - RAW_TTL: 'IP_DEFAULT_TTL'
    - LWIP_TCP: 'true'
    - TCP_TTL: 'IP_DEFAULT_TTL'
    - TCP_QUEUE_OOSEQ: 'false'
    - TCP_MSS: '(1500 - 40)'
    - TCP_SND_BUF: '(6 * TCP_MSS)'
    - TCP_SND_QUEUELEN: '(3 * TCP_SND_BUF) / TCP_MSS'
    - TCP_WND: '(2 * TCP_MSS)'
    - TCP_LISTEN_BACKLOG: 'true'
    - TCP_DEFAULT_LISTEN_BACKLOG: '0xFF'
    - LWIP_UDP: 'true'
    - UDP_TTL: 'IP_DEFAULT_TTL'
    - LWIP_STATS: 'false'
    - LWIP_PROVIDE_ERRNO: 'true'
    - CHECKSUM_BY_HARDWARE: 'true'
    - LWIP_DEBUG: 'true'
    - custom_opts: ''
    - modules_include: ''
    - mpu_init:
      - mpu_init_component: 'MPU'
    - time_init: 'false'
    - user_preinit: 'true'
    - user_init:
      - initFunctionID: 'lwIP_interface_init'
    - lwip_init: 'true'
    - ifConfig:
      - 0:
        - ethernetif_config_struct: []
        - netif_id: 'netif0'
        - interface: 'enet'
        - netif_mode: 'ipv4'
        - ip_assignment: 'dynamic'
        - ipv4Config:
          - ip_addr:
            - addr: '0.0.0.0'
          - netmask:
            - addr: '255.255.255.0'
          - gateway:
            - addr: '0.0.0.0'
        - netif_function_name: 'defaultFn'
        - netif_input_function_name: 'defaultInputFn'
        - mac_address:
          - useSiliconId: 'true'
          - addr: 'FF-FF-FF-FF-FF-FF'
        - link_timeout: '5000'
        - phyConfig:
          - phy_driver: 'custom:phylan8720a_ops'
          - phy_addr: '0x0'
          - phy_res_type: 'phy_lan8720a_resource_t'
          - mdioConfig:
            - mdioResources: []
            - enetConfig:
              - peripheralSelect: 'ENET0'
              - timing:
                - globalClockConfig:
                  - clockSource: 'GlobalClock'
                  - clockSourceFreq: 'BOARD_BootClockPLL100M'
              - mcx_enet_config:
                - phyTiming:
                  - refClockConfig:
                    - clockSource: 'EnetRefClock'
                    - clockSourceFreq: 'ClocksTool_DefaultInit'
              - enableUserInit: 'false'
              - user_init:
                - initFunctionID: 'ENET_communication_init'
    - lwip_codegenerator: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
/* Network interface structure */
struct netif lwIP_netif0;
/* PHY handle */
static phy_handle_t lwIP_netif0_phy_handle;
/* PHY resource */
phy_lan8720a_resource_t lwIP_netif0_phy_resource;

ethernetif_config_t lwIP_netif0_enet_config = {
  .phyHandle = &lwIP_netif0_phy_handle,
  .phyAddr = LWIP_NETIF0_PHY_ADDRESS,
  .phyOps = LWIP_NETIF0_PHY_OPS,
  .phyResource = LWIP_NETIF0_PHY_RESOURCE,
  .srcClockHz = LWIP_NETIF0_ENET_PERIPHERAL_CLK_FREQ,
#ifdef LWIP_NETIF0_MAC_ADDRESS
  .macAddress = LWIP_NETIF0_MAC_ADDRESS,
#endif
};

static void lwIP_init(void) {
  /* lwIP user physical abstraction initialization */
  lwIP_interface_init();
  /* lwIP module initialization */
  lwip_init();
  /* MCX ENET peripheral initialization */
  /* MCX ENET clock enable */
  (void)CLOCK_EnableClock(s_enetClock[ENET_GetInstance(LWIP_NETIF0_ENET_PERIPHERAL)]);
  /* MCX ENET set SMI (serial management interface) */
  ENET_SetSMI(LWIP_NETIF0_ENET_PERIPHERAL, LWIP_NETIF0_ENET_PERIPHERAL_CLK_FREQ);

#ifndef LWIP_NETIF0_MAC_ADDRESS
  /* Set special address for each chip. */
  (void)SILICONID_ConvertToMacAddr(&lwIP_netif0_enet_config.macAddress);
#endif
  /* lwIP network interface initialization */
  netif_add(&lwIP_netif0, NULL, NULL, NULL, &lwIP_netif0_enet_config, ethernetif0_init, ethernet_input);
  netif_set_default(&lwIP_netif0);
  netif_set_up(&lwIP_netif0);
  /* lwIP interface auto-negotiation check */
  while (ethernetif_wait_linkup(&lwIP_netif0, 5000UL) != ERR_OK) {
    PRINTF("PHY Auto-negotiation failed. Please check the cable connection and link partner setting.\r\n");
  }
  /* lwIP DHCP initialization */
  dhcp_start(&lwIP_netif0);
}

/***********************************************************************************************************************
 * USBFS0 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'USBFS0'
- type: 'usb'
- mode: 'host'
- custom_name_enabled: 'false'
- type_id: 'usb_2.8.0'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'USBFS0'
- config_sets:
  - hostSettings:
    - max_power: '500'
    - hub_support: 'true'
    - interfaces:
      - 0:
        - interface_class: 'kClassHid'
        - setting_hid:
          - interface_name: 'HID Mouse'
          - subclass: 'kSubclassBootInterface'
          - protocol: 'kProtocolMouse'
          - implementation: 'kImplementationMouse'
          - quick_selection: 'QS_INTERFACE_HID_MOUSE'
      - 1:
        - interface_class: 'kClassHid'
        - setting_hid:
          - interface_name: 'HID Generic'
          - subclass: 'kSubclassBootInterface'
          - protocol: 'kProtocolNone'
          - implementation: 'kImplementationGeneric'
  - commonSettings:
    - mpu_init:
      - mpu_init_component: 'MPU'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

static void USBFS0_init(void) {
  USB_HostApplicationInit();
}

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/
static void BOARD_InitPeripherals_CommonPreInit(void)
{
  /* Enable clock gate of the FLEXIO0 peripheral. */
  SYSCON0->AHBCLKCTRL2 |= SYSCON_AHBCLKCTRL2_FLEXIO_MASK;
}

static void BOARD_InitPeripherals_CommonPostInit(void)
{
  /* Enable interrupt USB_INTERRUPT_IRQN request in the NVIC */
  EnableIRQ(USB_INTERRUPT_IRQN);
}

void BOARD_InitPeripherals(void)
{
  /* Common pre-initialization */
  BOARD_InitPeripherals_CommonPreInit();
  /* Global initialization */
  ARM_MPU_Disable();

  /* Initialize components */
  LP_FLEXCOMM4_init();
  WUU0_init();
  LP_FLEXCOMM0_init();
  FLEXIO0_init();
  FLEXSPI0_init();
  CDOG0_init();
  GPIO0_ALIAS1_init();
  CRC0_init();
  lwIP_init();
  USBFS0_init();
  /* Common post-initialization */
  BOARD_InitPeripherals_CommonPostInit();
}

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void)
{
  BOARD_InitPeripherals();
}
